env:
  node: true
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules: {
  "no-console": ["error",
    {
      allow: ["warn", "error"]
    }],
  "no-trailing-spaces": "error",
  "@typescript-eslint/no-var-requires": "off",
  "react/prop-types": "error",
  "no-unused-vars": "error",
  "no-undef": "error",
  "@typescript-eslint/no-explicit-any": ["off"],
  "@typescript-eslint/no-non-null-assertion": "off",
  "@typescript-eslint/explicit-module-boundary-types": [
    "error",
    {
      "allowedNames": ["render", "componentDidMount", "componentWillReceiveProps"]
    }
  ],
}
parser: "@typescript-eslint/parser"
settings:
  react:
    version: detect


